import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { cn } from "@/lib/utils";

import { Providers } from "./providers";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const classes = cn(inter.className, "bg-zinc-200 dark:bg-zinc-800");

  return (
    <html suppressHydrationWarning lang="en">
      <body className={classes}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
